REFACTOR:{Home work - Logger} added value message
yana-sindiakova/yanaSindiakova pull request #5
Opened 2021-11-28 20:38 UTC by yana-sindiakova

2021-11-28 20:59 UTC, apollyonix requested changes
Можно удалить неиспользуемые переменную и методы

2021-11-28 20:59 UTC, apollyonix commented on src/Lesson9/Logger.java
> +    private static String message;
Лишняя переменная получилась, по факту она не используется

2021-11-28 20:59 UTC, apollyonix commented on src/Lesson9/Logger.java
> +        return message;
И, соответственно, лишние методы для этой переменной

2021-11-28 20:59 UTC, apollyonix commented on src/Lesson9/Logger.java
> +    public static void setLogger(LoggerType type, String message) {
Вот так вот вообще отлично)

2021-11-29 08:58 UTC, yana-sindiakova commented on src/Lesson9/Logger.java
> +    public static void setLogger(LoggerType type, String message) {
Все виправила

2021-11-29 09:01 UTC, apollyonix approved these changes
Супер)

2021-11-29 09:01 UTC, merged